= Popular Movie Store

== Overview

This https://projects.spring.io/spring-boot/[Spring Boot] based application will demonstrate the the following,

* Stateful application redeployments on https://kubernetes.io/[Kubernetes]/https://www.openshift.com/[OpenShift]jbo
* Using http://infinispan.org/[Inifinispan] with https://projects.spring.io/spring-boot/[Spring Boot] for HTTP session caching
and management
* Application state surviving across https://martinfowler.com/bliki/CanaryRelease.html[canary releases]

Refer to https://github.com/kameshsampath/jdg/wiki/Popular-Movie-Store[WIKI] for information on how
build and deploy the application

== License

Copyright 2017 Kamesh Sampath

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.