---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "${project.artifactId}"
spec:
  replicas: 2
  template:
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: "-Xms128m -Xmx256m -Djava.net.preferIPv4Stack=true"
        name: "${project.artifactId}"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        livenessProbe:
          httpGet:
            port: http
            path: /areyoualive
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            port: http
            path: /areyouready
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
