---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "${project.artifactId}"
spec:
  replicas: 2
  template:
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: "-Xms128m -Xmx512m -Djava.net.preferIPv4Stack=true"
        - name: OPENSHIFT_KUBE_PING_LABELS
          value: "project=${project.artifactId}"
        - name: OPENSHIFT_KUBE_PING_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        name: "${project.artifactId}"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8888
          name: jgroups-cluster
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        livenessProbe:
          httpGet:
            port: http
            path: /aliveandwell
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            port: http
            path: /readyornot
          initialDelaySeconds: 30
